title: Ming Li
name: Ming Li

permalink: pretty
show_excerpts: false

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      
collections:
  posts:
    output: true
    permalink: /notes/:title
  cs70:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "tufte"
      use_math: true
  -
    scope:
      path: ""
      type: "cs70"
    values:
      layout: "center"
      use_math: true
  -
    scope:
      path: ""
    values:
      layout: "center"
      use_math: false
