name: Ming Li
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
gems:
  - jekyll-sitemap
      
collections:
  notes:
    output: true
    permalink: /:collection/:name
  cs70:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
    values:
      layout: tufte