name: Ming Li
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
  projects:
    output: true
    permalink: /projects/:path/
  notes:
    output: true
    permalink: /notes/:path/